 var db= {
    db: 'reaction',
    Accounts: 'Accounts',
    AppSettings : 'AppSettings',
    Assets : 'Assets',
    Cart : 'Cart',
    Catalog : 'Catalog',
    Discounts : 'Discounts',
    Emails : 'Emails',
    FlatRateFulfillmentRestrictions : 'FlatRateFulfillmentRestrictions',
    Groups : 'Groups',
    Jobs : 'Jobs',
    NavigationItems : 'NavigationItems',
    NavigationTrees : 'NavigationTrees',
    Orders : 'Orders',
    Packages : 'Packages',
    Products : 'Products',
    Shipping : 'Shipping',
    Shops : 'Shops',
    SimpleInventory : 'SimpleInventory',
    Sitemaps : 'Sitemaps',
    Surcharges : 'Surcharges',
    Tags : 'Tags',
    Taxes : 'Taxes',
    cfs_Media_filerecord : 'cfs.Media.filerecord',
    meteor_accounts_loginServiceConfiguration : 'meteor_accounts_loginServiceConfiguration',
    meteor_oauth_pendingCredentials : 'meteor_oauth_pendingCredentials',
    meteor_oauth_pendingRequestTokens : 'meteor_oauth_pendingRequestTokens',
    roles : 'roles',
    users : 'users',
    SolicitudDeValidacion : 'SolicitudDeValidacion',
    Empresa: 'Empresa'
};

export default db;